### ISSUE TITLE
Working Glitch example using AFrame

### ISSUE THREAD

**Issue by Utopiah** [meta-quest/immersive-web-emulation-runtime#2]
Hi, just gave the documentation a test at https://glitch.com/edit/#!/iwer-on-aframe?path=index.html relying on the CDN import example https://meta-quest.github.io/immersive-web-emulation-runtime/getting-started.html#import-iwer-from-a-cdn

Unfortunately it leads to 

```
Uncaught TypeError: The specifier “gl-matrix” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”. XRDevice.js:16:28
```

while using 

```html
<script type="importmap">
	{
		"imports": {
			"iwer": "https://unpkg.com/iwer@1.0.0/lib/index.js"
		}
	}
</script>
<script type="module">
import { XRDevice, metaQuest3 } from 'iwer';

const xrDevice = new XRDevice(metaQuest3);
xrDevice.installRuntime();

console.log(xrDevice)
</script>
```

so wondering what should be done.

**Comment by msub2** [comment]
Try adding gl-matrix to the importmap as well, I remixed your glitch and that seems to have fixed the error

https://glitch.com/edit/#!/wiry-marble-tilapia

**Comment by Utopiah** [comment]
Thanks @msub2 it does indeed remove the error, yet if I run `xrDevice.position.y++` I don't see a visual change, so I'm wondering if that's the expected behavior or if this makes 2 different instances and thus don't reflect back what should be a camera change.

**Comment by felixtrz** [comment]
@msub2 thanks for jumping in!

@Utopiah thanks for raising this issue! What's happening here is that IWER wasn't injected before aframe is able to run - when aframe first runs on the page, it will try to detect whether there is native WebXR implementation by looking at the navigator.xr object. In your code, IWER was injected after aframe script is run, causing aframe to not find native WebXR implementation at start up, and aframe injected its only WebVR polyfill as a result.

**Comment by felixtrz** [comment]
I remixed your project and hooked up some keyboard shortcuts that controls the camera movement (you need to click on the vr button first to use those): https://glitch.com/~bird-curvy-quartz

<img width="586" alt="Screenshot 2024-07-08 at 3 07 07 PM" src="https://github.com/meta-quest/immersive-web-emulation-runtime/assets/11973041/18f4dbce-491c-4d4e-9e02-4d694d6591be">

**Comment by felixtrz** [comment]
It's kinda tricky, and I have this point documented here: https://meta-quest.github.io/immersive-web-emulation-runtime/getting-started.html#creating-an-xrdevice-and-installing-the-runtime

But probably not noticeable enough and I've a feeling more folks are gonna run into this issue. Sorry for the confusion!

**Comment by felixtrz** [comment]
> Try adding gl-matrix to the importmap as well, I remixed your glitch and that seems to have fixed the error
> 
> https://glitch.com/edit/#!/wiry-marble-tilapia

Alternatively, instead of importing the /lib/index.js and having to include gl-matrix as well, just import the /build/iwer.module.js:

```html
<script type="importmap">
	{
		"imports": {
			"iwer": "https://unpkg.com/iwer@<version>/build/iwer.module.js"
		}
	}
</script>
```
Check out my threejs integration example: https://glitch.com/edit/#!/iwer-three-example

**Comment by felixtrz** [comment]
Added a few framework-specific integration examples on Glitch:
- Three.js: https://glitch.com/edit/#!/iwer-three-example
- Babylon.js: https://glitch.com/edit/#!/iwer-babylon-example
- A-Frame: https://glitch.com/edit/#!/iwer-aframe-example

**Comment by felixtrz** [comment]
Marking issue as closed

**Comment by Utopiah** [comment]
Could the AFrame example also include hand support?

I briefly tried yesterday and today to get hands working but despite `xrDevice.primaryInputMode = 'hand'` and `xrDevice.controllers.left.connected = false` while `xrDevice.hands.right.connected` is `true` and changing hand positions I still do not see any hands.

**Comment by Utopiah** [comment]
Maybe this could be helpful for others too, namely 2 pinching helpers and some example of animations using AFRAME.ANIME within a testing scenario : 

```javascript
unPinchHand = (side="right") => AFRAME.ANIME( { targets: xrdevice.hands.side, easing: 'linear', update: function(anim) { xrdevice.hands[side].updatePinchValue(1-anim.progress/100) }  })
pinchHand = (side="right")  => AFRAME.ANIME( { targets: xrdevice.hands.side, easing: 'linear', update: function(anim) { xrdevice.hands[side].updatePinchValue(anim.progress/100) }  })

      // import IWER and inject runtime before aframe script is run
      // so that aframe can pick up "native" webxr implementation (IWER)
      const xrDevice = new IWER.XRDevice(IWER.metaQuest3);
      xrDevice.installRuntime();
      window.xrdevice = xrDevice;

        const rightHand = xrDevice.hands['right'];
        setTimeout( _ => AFRAME.scenes[0].enterVR(), 500 ) // not very clean...
        t = 1
        setTimeout( _ => {
                let targetSelector = "[value=a-sky]"
                let pos = document.querySelector( targetSelector ).getAttribute("position") // assume no rotation offset
                rightHand.position.set(pos.x, pos.y,  pos.z )
                pinchHand()
        }, ++t*1000 )
        setTimeout( _ => {
                // toggleAnchors() // useful to debug
                rightHand.position.set(0.3, 1.5, -.6);
                // prints getClosestTargetElements on released rather than on pinched
        }, ++t*1000 )
        setTimeout( _ => unPinchHand() , ++t*1000 )
        setTimeout( _ => xrDevice.hands['right'].position.set(0.1, 1.8, -.6), ++t*1000 )
        setTimeout( _ => AFRAME.ANIME( { targets: xrdevice.hands.right.position, x:1, y:1.5, z:-1, easing: 'linear', loop: true, direction: 'alternate' }), ++t*1000 )

```

**Comment by Utopiah** [comment]
How I'm currently using it https://git.benetou.fr/utopiah/spasca-fot-sloan-q2/src/branch/main/data/index.html#L16
